### ISSUE TITLE
[Feature Request] Named export

### ISSUE THREAD

**Issue by Meligy** [ianschmitz/react-lazy-with-preload#18]
Hello,
Can we have a named import `lazy` in addition to the default export?

This is not about whether default vs named imports are better. It's just that with the additional import, VS Code (and other IDEs) will be able to suggest the package when someone writes `lazy(...)`. Right now the only suggested option is importing `lazy` from react.

It doesn't have to be named `lazy`. `lazyWithPreload` or something similar would work too.
It's more expressive even. The only argument for `lazy` is that it's easier to swap react's `lazy`.

**Comment by ianschmitz** [comment]
Released in [v2.2.0](https://github.com/ianschmitz/react-lazy-with-preload/releases/tag/v2.2.0)

**Comment by Meligy** [comment]
Thanks a lot ❤️
