### ISSUE TITLE
Forward ref

### ISSUE THREAD

**Issue by adi518** [ianschmitz/react-lazy-with-preload#3]
Getting this warning:
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

React `lazy` forwards ref out of the box (I think it was added in `16.8`) and it's used in this library, so any idea why?

**Comment by ianschmitz** [comment]
Thanks for reporting this. Sounds like a legitimate issue that should be fixed by #4.

**Comment by ianschmitz** [comment]
Should be fixed in `2.0.1`.
